#!/usr/bin/env bash
set -euo pipefail

TFVARS_FILE=./terraform_test_kubernetes_executor.tfvars

# Read the namespace from the tfvars and derive the model name from the
# shared hash suffix that setup_env.sh used for both.
KUBERNETES_NAMESPACE=$(grep 'namespace' "$TFVARS_FILE" | sed -E 's/.*"([^"]+)".*/\1/')
hash=${KUBERNETES_NAMESPACE##*-}
MODEL_NAME="airflow-demo-$hash"

# Tear down the juju model and the kubernetes namespace
juju destroy-model "$MODEL_NAME" --no-prompt --destroy-storage --force
kubectl delete ns "$KUBERNETES_NAMESPACE" --ignore-not-found

# Remove terraform autogenerated state and lock files
rm -rf .terraform .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup

# Revert the tfvars edits that setup_env.sh made
sed -i '/^model_uuid/d' "$TFVARS_FILE"
sed -i "s|namespace  = \"$KUBERNETES_NAMESPACE\"|namespace  = \"airflow-executor-workers\"|" "$TFVARS_FILE"
