set export := true

default:
    @just --list

initialize:
    #!/usr/bin/bash
    if [ ! -d ".terraform" ]; then
        terraform init -backend=false
    fi

destroy-model:
    juju destroy-model --no-prompt --destroy-storage airflow-test || true

add-model: (destroy-model)
    juju add-model airflow-test

[private]
validate_test_tfvars variables_file:
    #!/usr/bin/bash

    set -euxo pipefail
    MODEL_UUID=$(juju show-model airflow-test --format=json | jq -r '."airflow-test"["model-uuid"]')
    if ! juju show-model "${MODEL_UUID}" >/dev/null 2>&1; then
        exit 1
    fi
    echo "model_uuid = \"${MODEL_UUID}\"" > "${variables_file}"

fmt: (initialize)
    terraform fmt -recursive

validate: (initialize)
    terraform validate

lint:
    tflint

apply variables_file: (initialize)
    terraform apply -auto-approve -var-file="${variables_file}"

destroy variables_file:
    #!/usr/bin/bash
    set -euxo pipefail
    if [ ! -f "${variables_file}" ]; then
        exit 1
    fi
    terraform destroy -auto-approve -var-file="${variables_file}" || true
    echo "Forcing model cleanup..."
    juju destroy-model --no-prompt --destroy-storage airflow-test --force || true

    rm "${variables_file}"

test:
    #!/usr/bin/bash
    set -euxo pipefail

    trap 'just destroy "terraform_test.tfvars"' EXIT

    just add-model

    just validate_test_tfvars "terraform_test.tfvars"

    just apply "terraform_test.tfvars"

    juju wait-for model airflow-test \
        --query='forEach(applications, app => app.status == "active")' \
        --timeout=1100s
