# .github/workflows/terraform-checks.yaml
name: Terraform checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
  workflow_call:

jobs:
  pull-request-terraform-checks:
    name: PR Terraform checks (${{ matrix.just-target }})
    strategy:
      matrix:
        just-target:
          - test
          - test-executor
      fail-fast: false
    # FIXME: change after the branch has been merged to main
    uses: canonical/workflows-team/.github/workflows/terraform.yaml@dnplas-make-test-targets-inputs
    with:
      module-directory: ./modules/charmed-airflow
      just-target: ${{ matrix.just-target }}
      timeout-minutes: 40
