# .github/workflows/terraform-checks.yaml
name: Terraform checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
  workflow_call:

jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -euxo pipefail
          
          goss_base_url="https://github.com/goss-org/goss/releases/latest/download"
          curl -L ${goss_base_url}/kgoss -o "/usr/local/bin/kgoss"
          chmod +rx "/usr/local/bin/kgoss"
  pull-request-terraform-checks:
    name: PR Terraform checks
    uses: canonical/workflows-team/.github/workflows/terraform.yaml@main
    with:
      module-directory: ./modules/charmed-airflow
      timeout-minutes: 40
